name: Build
run-name: "Build"
on:
  pull_request: { }
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR: Builds
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CMAKE_BUILD_PARALLEL_LEVEL: 3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-latest ]
        buildType: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        shell: bash
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" .
      - name: Build
        shell: bash
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.buildType }} --parallel 4